### ISSUE TITLE
Micro Plugin with other features v1 roadmap 

### ISSUE THREAD

**Issue by anikethsaha** [pluggingIn/bundlesize-webpack-plugin#1]
# Motivation: Divide and concur  😁 

[Branch](https://github.com/anikethsaha/webpack-plugin-bundlesize/tree/micro-plugin-development)

## TODOs
- [ ] **Monorepo(s)** for builtin microplugin

- [ ] **Typescript** Migration

- [ ] To implement the current in **watchRun** hook

- [ ] To recommend some optimizations when size exceeding - **MicroPlugin**

- [ ] To implement the **logo** and make the looks better

- [ ] To suggest optmizations **MicroPlugin List**
   1. [ ] read the config and check whether the splitchunk is implemented or not

   2. [ ] Minify plugin

   3. [ ] Codespliting suggestion
